variable db_engine_version {}
variable db_instance_class {}
variable db_name {}
variable db_username {}
variable db_password {}
variable db_subnet_ids {}
variable db_parameter_group_name {}
variable "tags" {}
variable "vpc_id" {}
variable "ghost_asg_sg" {}